### PR TITLE
Requests version

### PR DESCRIPTION
**Pull request by smartcontracts**
Final.py requests version. Requires `requests`. Multi-threaded, should handle all of the signups at the same time (might want to decrease threads if computer can't create enough virtual threads).

### CODE REVIEW

**Review by eggins — APPROVED** [review]
I approve this because the code isnt washed and he has some clue about whathe is doing.

**Comment by yousefissa** [comment]
Thanks Ayinope! Thanks for your approval too eggins, we all needed it.

**Comment by eggins** [comment]
hahaha.
the main thing here is i dont want to beef. just please stop acting like you are the best developer on the TL.

**Comment by yousefissa** [comment]
Yet you came at my code multiple times with insults instead of providing helpful criticisms? Then you dedicated nearly 12 hours of bashing me on Twitter? No one is asking like they're the best dev on Twitter. Please show me where I even made such a statement. I'm always open to improvements and suggestions, no need to be an ass about it though.  You can't "not want beef" when you're coming at people. I have said nothing wrong to you at all.

**Comment by eggins** [comment]
DM me on twitter. I guess its more the group you associate with that gives me the shits.

**Comment by smartcontracts** [comment]
FYI: I think the endpoint for final referrals is down right now so I'm getting timeouts with both methods

**Comment by yousefissa** [comment]
Yah their website is beyond unusable right now.

**Pull request merged**
